languageCode = "en-us"
title = "Open Source Club"
description = "At The Ohio State University"
theme = "kube"
paginate = 15

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Events"
    url = "/events"

[params]
    # Use this to display a message on  the home page
    message = "Meeting 09/27, 17:30, Caldwell 115"

    twitter = "osuosc"
    github = "OSUOSC"
